name: 构建 Vaultwarden

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: install rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: aarch64-unknown-linux-musl

    - name: 克隆代码
      run: |
        git clone --depth 1 https://github.com/dani-garcia/vaultwarden.git vaultwarden

    - name: 执行编译
      run: |
        cd vaultwarden
        rustup target add aarch64-unknown-linux-musl
        rustup default aarch64-unknown-linux-musl
        cargo build -r --target aarch64-unknown-linux-musl
