name: 构建 Vaultwarden

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04-arm

    steps:
    - name: install rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: aarch64-unknown-linux-musl

    - name: 安装依赖
      run: |
        apt-get install -y build-essential git pkg-config libssl-dev libsqlite3-dev libmariadb-dev-compat libmariadb-dev 

    - name: 克隆代码
      run: git clone --depth 1 https://github.com/dani-garcia/vaultwarden.git vaultwarden

    - name: 安装aarch64工具链
      working-directory: vaultwarden
      run: rustup target add aarch64-unknown-linux-musl
        
    - name: 执行编译
      working-directory: vaultwarden
      run: cargo build -r --target aarch64-unknown-linux-musl --features sqlite
